### ISSUE TITLE
"done is not a function" migrating from 1.x to 2.0 using adal angular

### ISSUE THREAD

**Issue by nicoschmitt** [AzureAD/passport-azure-ad#125]
I'm using adal angular 2.0 experimental.

TypeError: done is not a function
    at Strategy.jwtVerify [as _verify] (C:\Users\nicolass\Documents\GitHub\nicontoso\node_modules\passport-azure-ad\lib\bearerstrategy.js:148:7)
    at Strategy.authenticate (C:\Users\nicolass\Documents\GitHub\nicontoso\node_modules\passport-http-bearer\lib\strategy.js:132:10)
    at attempt (C:\Users\nicolass\Documents\GitHub\nicontoso\node_modules\passport\lib\middleware\authenticate.js:348:16)
    at authenticate (C:\Users\nicolass\Documents\GitHub\nicontoso\node_modules\passport\lib\middleware\authenticate.js:349:7)
    at Layer.handle [as handle_request] (C:\Users\nicolass\Documents\GitHub\nicontoso\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\nicolass\Documents\GitHub\nicontoso\node_modules\express\lib\router\route.js:131:13)

**Comment by dhodgin** [comment]
I think this is fixed in next version. I wrote a PR to deal with this. a temp fix is to look at the BearerStrategy.call line in bearerstrategy.js at the util._extend() call. remove the {} first argument because _extend only accepts 2 arguments not 3. so the req object is not passed back to verify which means done is undefined.

**Comment by nicoschmitt** [comment]
ok thanks
