### ISSUE TITLE
oniyi-object-transform at "^1.0.0" pulls 1.2.0 which breaks node 4.x compatibility

### ISSUE THREAD

**Issue by nss213** [AzureAD/passport-azure-ad#246]
This is really an issue with oniyi-object-transform's latest release, but it seems like it could be remedied by pinning it to version 1.1.3 instead of ^1.0.0 so that we can move forward without waiting for oniyi-object-transform to be fixed in npm. I'm currently using v 2.0.3 of passport-azure-ad,  but the package.json for 3.x is also the same. Basicaly version 1.2.0 of oniyi-object-transform seems to require node >= 6 and it fails with a syntax error in node 4.x.

I see the following with 1.2 on node 4.2.4:
```
> const foo = require('oniyi-object-transform');
SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/navtej/code/scratch/node_modules/oniyi-object-transform/lib/index.js:4:16)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
```

**Comment by lovemaths** [comment]
@nss213 We just did a new release (v3.0.2) to remove the dependency on oniyi-object-transform, please check it out. Thanks!
