### ISSUE TITLE
Unhandled error in `_getAccessTokenBySecretOrAssertion`

### ISSUE THREAD

**Issue by abramz** [AzureAD/passport-azure-ad#320]
Some of our users are experiencing issues logging in with MSFT OAuth. The only thing we have in our server logs is this unhandled error from the `oidcstrategy`.  How do we resolve this? Why is this the error we got instead of something that our developers could use to fix the problem?

```
TypeError: Cannot read property 'toLowerCase' of undefined
    at self._getAccessTokenBySecretOrAssertion (D:\home\site\wwwroot\node_modules\passport-azure-ad\lib\oidcstrategy.js:1108:25)
    at oauth2._request.e (D:\home\site\wwwroot\node_modules\passport-azure-ad\lib\oidcstrategy.js:1327:7)
    at passBackControl (D:\home\site\wwwroot\node_modules\passport-azure-ad\node_modules\oauth\lib\oauth2.js:125:9)
    at IncomingMessage.<anonymous> (D:\home\site\wwwroot\node_modules\passport-azure-ad\node_modules\oauth\lib\oauth2.js:143:7)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by lovemaths** [comment]
@abramz This is duplicate issue with #317 , I will do a release within the next one or two hours and let you know. Please use the code in dev branch for now.
