### ISSUE TITLE
Token signed with expired key causes crash: 'a key with kid %s cannot be found'

### ISSUE THREAD

**Issue by fikkatra** [AzureAD/passport-azure-ad#335]
An API call made with an old token (expired June 14, 2017) caused our app to crash. I assume the key with which the token was originally signed, is no longer available.

An error '**a key with kid %s cannot be found**' was thrown, causing the app to crash.

The desired behavior would be to just return 401, instead of throwing an error. Now, any malicious user can crash the app by just sending an HTTP request. 

Awaiting a proper solution, is there at least a hook to catch the error?

We use version: 3.0.6 with BearerStrategy.
Route setup: `app.all('/api*', passport.authenticate('oauth-bearer', { session: false }));`

This is the stacktrace:
```
Error: a key with kid %s cannot be found
    at Metadata.generateOidcPEM (<projectpath>\node_modules\passport-azure-ad\lib\metadata.js:146:11)
    at Strategy.jwtVerifyFunc [as jwtVerify] (<projectpath>\node_modules\passport-azure-ad\lib\bearerstrategy.js:291:23)
    at Strategy.authenticate.async.waterfall (<projectpath>\node_modules\passport-azure-ad\lib\bearerstrategy.js:461:19)
    at fn (<projectpath>\node_modules\passport-azure-ad\node_modules\async\lib\async.js:746:34)
    at <projectpath>\node_modules\passport-azure-ad\node_modules\async\lib\async.js:1213:16
    at <projectpath>\node_modules\passport-azure-ad\node_modules\async\lib\async.js:166:37
    at <projectpath>\node_modules\passport-azure-ad\node_modules\async\lib\async.js:706:43
    at <projectpath>\node_modules\passport-azure-ad\node_modules\async\lib\async.js:167:37
    at Immediate.<anonymous> (<projectpath>\node_modules\passport-azure-ad\node_modules\async\lib\async.js:1206:34)
```

**Comment by lovemaths** [comment]
@fikkatra We fixed this bug in version 3.0.7, please update your version to the newest version (current version is 3.0.8).
