### ISSUE TITLE
Response not defined in oauthConfig leads to res.cookie undefined

### ISSUE THREAD

**Issue by timelf123** [AzureAD/passport-azure-ad#344]
```
TypeError: Cannot read property 'cookie' of undefined
    at CookieContentHandler.add (C:\Dev\ideawake\node_modules\passport-azure-ad\lib\cookieContentHandler.js:128:6)
    at Strategy.flowInitializationHandler [as _flowInitializationHandler] (node_modules\passport-azure-ad\lib\oidcstrategy.js:1328:32)
    at async.waterfall (node_modules\passport-azure-ad\lib\oidcstrategy.js:627:23)
```

In `CookieContentHandler.prototype.add`
```
console.log(res) -> undefined
  res.cookie('passport-aad.' + Date.now() + '.' + encrypted, 0, { maxAge: this.maxAge * 1000, httpOnly: true });
```

Route:
```
app.route('/api/auth/office365/callback')
        .post(passport.authenticate('azuread-openidconnect', {
          failureRedirect: loginPage
        }), users.authCallback);
```

**Comment by timelf123** [comment]
Didn't see that we have to explicitly pass in res oops
