### ISSUE TITLE
npm install on Windows gives errors

### ISSUE THREAD

**Issue by billti** [AzureAD/passport-azure-ad#353]
Looks like the error is as you depend on Bunyan, which depends on dtrace-provider. I get the below error in a new package when I do `npm install passport-azure-ad` or `npm install bunyan`. 

A search on the bunyan repro for node-gyp issues turns up a lot of hits :-/  (https://github.com/trentm/node-bunyan/search?q=node-gyp&type=Issues&utf8=%E2%9C%93). Not sure this breaks anything, but obviously errors on `npm install` are not reassuring.

```bat
npm install passport-azure-ad

> dtrace-provider@0.8.6 install C:\temp\pass\node_modules\dtrace-provider
> node-gyp rebuild || node suppress-error.js


C:\temp\pass\node_modules\dtrace-provider>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
MSBUILD : error MSB4025: The project file could not be loaded. Root element is missing.
gyp ERR! build error
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:159:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\temp\pass\node_modules\dtrace-provider
gyp ERR! node -v v9.3.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN pass@1.0.0 No description
npm WARN pass@1.0.0 No repository field.

+ passport-azure-ad@3.0.9
added 99 packages in 5.936s
```

**Comment by lovemaths** [comment]
@billti Thank you for pointing it out. We will remove the Bunyan dependency.

**Comment by lovemaths** [comment]
Closing the issue. Removing Bunyan dependency is part of enhancement #196
