### ISSUE TITLE
'bunyan' a dev dependency but used in metadata.js

### ISSUE THREAD

**Issue by jmhall** [AzureAD/passport-azure-ad#36]
I'm getting this error:

Error: Cannot find module 'bunyan'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/mhall/Documents/git/jls/node_modules/passport-azure-ad/lib/passport-azure-ad/metadata.js:31:14)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)

I assume because it's in devDependencies, but it's used in metadata.js.

**Comment by brandwe** [comment]
Fixed!
