### ISSUE TITLE
Possible regression on #7, using multiple certs? 

### ISSUE THREAD

**Issue by jmhall** [AzureAD/passport-azure-ad#37]
Before updating to 1.0.0 from npm this was working, but now I'm getting this:

Error: Invalid signature
    at SAML.validateResponse (/Users/mhall/Documents/git/jls/node_modules/passport-azure-ad/lib/passport-azure-ad/wsfedsaml.js:115:25)
    at Strategy._doAuthenticate (/Users/mhall/Documents/git/jls/node_modules/passport-azure-ad/lib/passport-azure-ad/wsfedstrategy.js:164:20)

I'm assuming this is related to #7?

**Comment by jmhall** [comment]
Maybe I'm doing something wrong...I updated my package.json to use 1.0.0 and started getting several errors.  I'm rolling back to 0.0.5 and the errors disappear.  Apologies if these issues are related to something I'm doing wrong with npm.

**Comment by brandwe** [comment]
Can you try the latest npm and make sure this is fixed?

**Comment by jmhall** [comment]
Sure, I'll follow back up on this later today
