### ISSUE TITLE
Malformed JSON web token causes crash

### ISSUE THREAD

**Issue by Daniel-Hope** [AzureAD/passport-azure-ad#375]
version: 3.0.12
Hi,
I am using the Bearer Strategy to check auth tokens fetched from AAD.
The library works well and handles the situation appropriately when there is a valid or expired token sent in the authorization header.
Next I tried taking a valid token, deleting a chunk out of the middle of it, then sending that to my node server. This resulted in the jwt JSON parser throwing and error causing the node instance to crash.

I tried surrounding the `passport.authenticate` with a try catch and it did not stop it from crashing.

```
const express = require('express');
const router = express.Router();
const logger = require('winston');
const passport = require('passport');
const BearerStrategy = require('passport-azure-ad').BearerStrategy;

const AAD_AUTH_CONFIG = {
  identityMetadata: 'https://login.microsofto... etc.',
  clientID: '<app guid>'
};

passport.use(new BearerStrategy(AAD_AUTH_CONFIG, function(token, done) {
  return done(null, token);
}));

router.use(passport.initialize());

router.get('/path', (request, response) => {
  try {
    logger.info("checkAuthToken");
    passport.authenticate('oauth-bearer', function(err, user, info) {
      logger.info("inside callback");
      logger.info(err);
      logger.info(user);
      logger.info(info);
      response.send("Some Data");
    })(request, response);
  } catch(err) {
    response.send("Runtime Error");
  }
});
```

This is what the logs look like when I send it a request.
```
2018-04-12 14:06:30 PID:4161 INFO checkAuthToken
undefined:1
{"aud":"<app guid>","iss":"<valid value>","iat"3�$F�V ... garbled json
                                                                                                                         ^

SyntaxError: Unexpected number in JSON at position 121
    at JSON.parse (<anonymous>)
    at Object.jwsDecode [as decode] (/node_modules/jws/lib/verify-stream.js:71:20)
    at Strategy.jwtVerifyFunc [as jwtVerify] (/node_modules/passport-azure-ad/lib/bearerstrategy.js:290:23)
    at async.waterfall (/node_modules/passport-azure-ad/lib/bearerstrategy.js:568:19)
    at fn (/node_modules/passport-azure-ad/node_modules/async/lib/async.js:746:34)
    at /node_modules/passport-azure-ad/node_modules/async/lib/async.js:1213:16
    at /node_modules/passport-azure-ad/node_modules/async/lib/async.js:166:37
    at /node_modules/passport-azure-ad/node_modules/async/lib/async.js:706:43
    at /node_modules/passport-azure-ad/node_modules/async/lib/async.js:167:37
    at Immediate._onImmediate (/node_modules/passport-azure-ad/node_modules/async/lib/async.js:1206:34)
2018-04-12 14:06:30 PID:4151 ERROR Worker 4161 died
```

Is there a way to catch this error and handle it myself or will it require a change in the library?

**Comment by MattheuM** [comment]
Also having the same issue, trying to open a pr to fix

**Comment by pkanher617** [comment]
#436 appears to have been merged, closing. Please open a new issue [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/new/choose) if you are still seeing problems.
