### ISSUE TITLE
BearerStrategy "TypeError: self.success is not a function"

### ISSUE THREAD

**Issue by oehm-smith** [AzureAD/passport-azure-ad#427]
i have posted this at https://stackoverflow.com/questions/56372349/azure-ad-open-bearerstrategy-typeerror-self-success-is-not-a-function with some more information.

Passport-Azure-AD version 4.1.0

I have set this up pretty-much like your doco:

```
    setup() {
        const findById = (id, fn) => {
            for (let i = 0, len = this.users.length; i < len; i++) {
                const user = this.users[i];
                if (user.sub === id) {
                    logger.info('Found user: ', user);
                    return fn(null, user);
                }
            }
            return fn(null, null);
        };

        this.bearerStrategy = new BearerStrategy(jwtOptions,
            (token: ITokenPayload, done: VerifyCallback) => {  
                findById(token.oid, (err, user) => {
                    if (err) {
                        return done(err);
                    }
                    if (!user) {
                        // 'Auto-registration'
                        logger.info('User was added automatically as they were new. Their oid is: ', token.oid);
                        this.users.push(token);
                        this.owner = token.oid;
                        return done(null, token);
                    }
                    this.owner = token.oid;
                    return done(null, user, token);
                });
            }
        );
        console.log(`setup bearerStrategy`);
    }
```

And run authentication (from middlewhere) using the following:

```
    authenticate(request: express.Request) {
        this.bearerStrategy.authenticate(request, {session: false});
    }

 ```

**NOTE  the documenation says to do the following but that is INCORRECT.  My working solution is shown just above**:

```
  server.get('/api/tasks', passport.authenticate('oauth-bearer', { session: false }), listTasks);  # WRONG IN DOCO
```

The options are like this:

```
const jwtOptions = {
    identityMetadata: 'https://login.microsoftonline.com/xyz/v2.0/.well-known/openid-configuration',
    clientID: '0123456789',
    loggingLevel: 'info',
    loggingNoPII: false,
    passReqToCallback: false
};
```

It fails on the line:

```                        
return done(null, token);
```

With:

```
[2019-05-29T13:49:33.479] [INFO ] [AUTHSERVICE_LOGGER] - User was added automatically as they were new. Their oid is:  123

/Users/bbos/dev/dhs/translate/translateboard/node_modules/passport-azure-ad/lib/bearerstrategy.js:565
        return self.success(user, info);
                    ^
TypeError: self.success is not a function
    at verified (/Users/bbos/dev/dhs/translate/translateboard/node_modules/passport-azure-ad/lib/bearerstrategy.js:565:21)
    at findById (/Users/bbos/dev/dhs/translate/translateboard/server/src/services/AuthService.ts:106:32)
    at findById (/Users/bbos/dev/dhs/translate/translateboard/server/src/services/AuthService.ts:87:20)
    at Strategy.bearerStrategy.passport_azure_ad_1.BearerStrategy [as _verify] (/Users/bbos/dev/dhs/translate/translateboard/server/src/services/AuthService.ts:97:17)
    at jwt.verify (/Users/bbos/dev/dhs/translate/translateboard/node_modules/passport-azure-ad/lib/bearerstrategy.js:363:19)
    at /Users/bbos/dev/dhs/translate/translateboard/node_modules/passport-azure-ad/lib/jsonWebToken.js:80:16
    at process._tickCallback (internal/process/next_tick.js:61:11)
```
If I look at the code, the self Object is only what is defined in BearerStrategy:

```
{
  "name": "oauth-bearer",
  "_options": {
    "identityMetadata": "https://login.microsoftonline.com/xyz/v2.0/.well-known/openid-configuration",
    "clientID": "0123456789",
    "loggingLevel": "info",
    "loggingNoPII": false,
    "passReqToCallback": false,
    "clockSkew": 300,
    "validateIssuer": true,
    "allowMultiAudiencesInToken": false,
    "audience": [
      "1234",
      "spn:1234"
    ],
    "isB2C": false,
    "_isCommonEndpoint": false
  }
}
```

I think `self` should also inherit from `Passport.Strategy`.  I believe this line in `node_modules/passport-azure-ad/lib/bearerstrategy.js` should make the inheritance happen:

```
util.inherits(Strategy, passport.Strategy);    // Line 205 of bearerstrategy.js
```

Is this a bug or is it something else that I am missing?

ps. Should `return done(null, user, token);` be `return done(null, token);`?

**Comment by oehm-smith** [comment]
Ok that was completely wrong.  I discussed this at https://stackoverflow.com/questions/56372349/azure-ad-open-bearerstrategy-typeerror-self-success-is-not-a-function and pointed to a further problem with the use of `async.waterfall`.  I will close this a create a new issue.
