### ISSUE TITLE
TypeError: this.fail is not a function

### ISSUE THREAD

**Issue by bonk-se** [AzureAD/passport-azure-ad#489]
My node server crashes when I get an authentication failure, since it can't handle the error message properly. Here's the crash log:

```
...\node_modules\passport-azure-ad\lib\bearerstrategy.js:602
  return this.fail(message);
              ^
TypeError: this.fail is not a function
    at Strategy.failWithLog (...\node_modules\passport-azure-ad\lib\bearerstrategy.js:602:15)
    at ...\node_modules\passport-azure-ad\lib\bearerstrategy.js:325:21
    at ...\node_modules\passport-azure-ad\lib\jsonWebToken.js:80:16
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
```

Just before the crash, the error log for an authentication error is printed, containing:
"authentication failed due to: invalid signature"
which matches the failWithLog-functions output

**Comment by jennyf19** [comment]
@bonk-se Are you using AAD or B2C?

**Comment by bonk-se** [comment]
@jennyf19 I was using AAD

**Comment by pkanher617** [comment]
@bonk-se Sorry for the late response here. We are currently in the design phase of a new version of this library, which can be tracked [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/projects/9). The timeline for the new library will be uploaded to our [msal js repo](https://github.com/AzureAD/microsoft-authentication-library-for-js).

Is this still an issue?

**Comment by bonk-se** [comment]
Unless the missing function has been added, I would think it's still an issue.

**Comment by jennyf19** [comment]
@pkanher617 will the issue in this library (passport.js) be resolved and released w/a fix?
