### ISSUE TITLE
In collectInfoFromReq: invalid state received in the request

### ISSUE THREAD

**Issue by SigurdMW** [AzureAD/passport-azure-ad#515]
I'm seeing this error `In collectInfoFromReq: invalid state received in the request` quite a lot, both locally and in production. From what I can understand, it's an issue where the state created by the library before you are redirected to the login page doesn't match the state that is provided on the callback after login. I haven't been able to figure out why. There are no steps that I have found to reproduce the issue, it will just happen from time to time when logging in. 

The issue happens when the user is redirected back to my application from the login-page, and my logs looks like this:
```
2020-09-14T11:36:37.535Z [a0fcda47-4424-4118-baa0-f52d8b3a608a] core - info: Parsing JSON retreived from the endpoint
2020-09-14T11:36:37.567Z [a0fcda47-4424-4118-baa0-f52d8b3a608a] core - info: Request to update the Open ID Connect Metadata
2020-09-14T11:36:37.707Z [a0fcda47-4424-4118-baa0-f52d8b3a608a] core - info: entering Strategy.prototype._flowInitializationHandler
2020-09-14T11:36:37.723Z [a0fcda47-4424-4118-baa0-f52d8b3a608a] core - info: We are sending the response_type:
2020-09-14T11:36:37.725Z [a0fcda47-4424-4118-baa0-f52d8b3a608a] core - info: We are sending the response_mode:
2020-09-14T11:36:58.261Z [5adaedc2-5027-445d-adf6-6220d2236d64] core - info: authentication failed due to: In collectInfoFromReq: invalid state received in the request
```

## About our setup: 
* Using B2C

### Package versions
* `passport-azure-ad@4.2.1`
* `express@4.16.3`
* `express-session@1.17.1`
* `redis@2.8.0`
* `connect-redis@4.0.3`

I have also seen the error when using `MemoryStorage` so I don't think it's related to Redis.

Possibly related to:
* #510 
* #423 
* #289 
* #390
* #462 
* #477

**Comment by lamilsage** [comment]
Hi,

I had the same issue, after investigation, I was able to see that I was loosing my session id time to time, mainly when I was taking all my time to validate the differents azure ad steps (password, double authentication ...). 
I use session storage.
I fixed the issue by forcing the session cookie sameSite value to none. Before it was just not set.

`this._session = {
            secret: <a_secret>,
            cookie: {
                secure: true,
                maxAge: env.SESSION_LIFETIME * 60 * 1000,
                sameSite: 'none' 
            },
            resave: true,
            saveUninitialized: true
        };`

**Comment by SigurdMW** [comment]
Interesting, thanks for letting me know @lamilsage. I'm in the same situation as you were before - `sameSite` is not set. I will try to set it to `None`. 
Do you have any idea why this should make a difference?

**Comment by lamilsage** [comment]
SameSite default value is Lax. 
https://developer.mozilla.org/fr/docs/Web/HTTP/Headers/Set-Cookie/SameSite. 
And apparently we lost session cookie when reaching the azure ad endpoint for login with a lax cookie.

**Comment by SigurdMW** [comment]
It could of course the issue, but since my error is only happening once every 20th time I try to log in or so, I'm a little hesitant to say this is the solution. If this was the issue - wouldn't it have failed every time?

**Comment by lamilsage** [comment]
I found some interesting articles 
- https://www.chromium.org/updates/same-site/test-debug
- https://www.chromium.org/updates/same-site?pli=1#20191101
- https://auth0.com/docs/sessions-and-cookies/samesite-cookie-attribute-changes?_ga=2.187307496.1959161806.1586731159-335697392.1581011225#actions-you-need-to-take
- https://docs.microsoft.com/en-us/azure/active-directory-b2c/cookie-definitions

I'm not totally sure, but maybe there is still a littler delay with Lax+Post

**Comment by lluisrojass** [comment]
Hi, 

https://www.chromestatus.com/feature/5088147346030592

Relevant:

> Note: Chrome will make an exception for cookies set without a SameSite attribute less than 2 minutes ago. Such cookies will also be sent with non-idempotent (e.g. POST) top-level cross-site requests despite normal SameSite=Lax cookies requiring top-level cross-site requests to have a safe (e.g. GET) HTTP method. Support for this intervention ("Lax + POST") will be removed in the future.

This introduced my issue. The B2C POST back would not contain the relevant session cookie if it was beyond the 2 minute limit. To get around this & the associated Safari/iOS bug, we need to sniff the UA and determine inclusion of the SameSite & Secure cookie flags.

**Comment by lluisrojass** [comment]
Here is a psuedo-code snippet with agents which reject `SameSite=None` flags. 

https://www.chromium.org/updates/same-site/incompatible-clients

**Comment by jeffwilcox** [comment]
Thanks @lluisrojass this helped me... we regenerate our session upon successfully authentication, but our unauthenticated users had an active session, so anyone who had an existing session and then went to sign-in would get the error.

Our interim fix to at least take advantage of the 2-minute window and reduce pain _until we can get SameSite sniffing working_ was to `req.session.regenerate` from our `/signin` page before redirecting to `/auth/azure` and the standard Passport routes. We also had to hoist any session properties we wanted to take along for the ride.

**Comment by SigurdMW** [comment]
Did anyone of you succeed in using `sameSite: "Lax"` configuration option? Seems to cause the error `In collectInfoFromReq: invalid state received in the request` every time for me. 
When changing from `form_post` to `query` `responseMode` in the configuration, `sameSite` "Lax" seems to work.

**Comment by lluisrojass** [comment]
@SigurdMW If you want to use a post-back approach, you need your cookie to behave like a third-party cookie. To achieve that, you need to deliver the`SameSite=none` flag on most modern UAs. 

This article was helpful for me: https://web.dev/samesite-cookies-explained/  
If you want to dive into the deep end you can follow this discussion: https://groups.google.com/a/chromium.org/g/blink-dev/c/AknSSyQTGYs/m/YKBxPCScCwAJ?pli=1

**Comment by 7coil** [comment]
For some reason, when a user fetches my `/microsoft` route and is redirected to `/microsoft/return`, this error occurs.
This error no longer occurs (for me at least in development) when the redirect route is the same as the original login route.

```js
router
  .use('/microsoft',
    multer().none(),
    passport.authenticate('azuread-openidconnect', {
      failureRedirect: '/fail'
    })
  )
  // .use('/microsoft/return',
  //   passport.authenticate('azuread-openidconnect', {
  //     failureRedirect: '/fail',
  //   })
  // )
```

![image](https://user-images.githubusercontent.com/13886925/97172278-bb474a00-1786-11eb-8dd4-918d57cb91f7.png)

**Comment by phawxby** [comment]
I've spent the last couple of days bashing my head on a wall with this one. There is definitely some kind of problem but I cannot find it. Fortunately we only use it to secure our dev tier, but it means we can no longer actually get to our dev tier. 

```
2020-11-03T14:40:40.040344336Z {"name":"AzureAD: OIDC Passport Strategy","hostname":"353022b0890a","pid":51,"level":30,"msg":"metadataUrl is: https://login.microsoftonline.com/SNIP/v2.0/.well-known/openid-configuration?x-client-SKU=passport-azure-ad&x-client-Ver=4.0.0","time":"2020-11-03T14:40:40.040Z","v":0}
2020-11-03T14:40:40.040948352Z {"name":"AzureAD: OIDC Passport Strategy","hostname":"353022b0890a","pid":51,"level":30,"msg":"received the following items in params: {\"policy\":null,\"cachekey\":\"https://login.microsoftonline.com/SNIP/v2.0/.well-known/openid-configuration?x-client-SKU=passport-azure-ad&x-client-Ver=4.0.0\",\"metadata\":{\"url\":\"https://login.microsoftonline.com/SNIP/v2.0/.well-known/openid-configuration?x-client-SKU=passport-azure-ad&x-client-Ver=4.0.0\",\"metadata\":null,\"authtype\":\"oidc\",\"loggingNoPII\":false}}","time":"2020-11-03T14:40:40.040Z","v":0}
2020-11-03T14:40:40.041822075Z {"name":"AzureAD: OIDC Passport Strategy","hostname":"353022b0890a","pid":51,"level":30,"msg":"entering Strategy.prototype._flowInitializationHandler","time":"2020-11-03T14:40:40.041Z","v":0}
2020-11-03T14:40:40.041938478Z {"name":"AzureAD: OIDC Passport Strategy","hostname":"353022b0890a","pid":51,"level":30,"msg":"We are sending the response_type:  id_token","time":"2020-11-03T14:40:40.041Z","v":0}
2020-11-03T14:40:40.042098282Z {"name":"AzureAD: OIDC Passport Strategy","hostname":"353022b0890a","pid":51,"level":30,"msg":"We are sending the response_mode:  form_post","time":"2020-11-03T14:40:40.041Z","v":0}


2020-11-03T14:40:42.929139718Z {"name":"AzureAD: OIDC Passport Strategy","hostname":"d2fcc02a239e","pid":51,"level":30,"msg":"authentication failed due to: In collectInfoFromReq: invalid state received in the request","time":"2020-11-03T14:40:42.928Z","v":0}
2020-11-03T14:40:42.954877772Z error: Error response to client {
2020-11-03T14:40:42.954914173Z   message: 'Unauthorized',
2020-11-03T14:40:42.954921073Z   stack: 'AuthenticationError: Unauthorized\n' +
2020-11-03T14:40:42.954925673Z     '    at allFailed (/home/site/wwwroot/node_modules/passport/lib/middleware/authenticate.js:172:21)\n' +
2020-11-03T14:40:42.954930273Z     '    at attempt (/home/site/wwwroot/node_modules/passport/lib/middleware/authenticate.js:180:28)\n' +
2020-11-03T14:40:42.954934873Z     '    at Strategy.strategy.fail (/home/site/wwwroot/node_modules/passport/lib/middleware/authenticate.js:302:9)\n' +
2020-11-03T14:40:42.954939473Z     '    at Strategy.failWithLog (/home/site/wwwroot/node_modules/passport-azure-ad/lib/oidcstrategy.js:1503:15)\n' +
2020-11-03T14:40:42.954944774Z     '    at /home/site/wwwroot/node_modules/passport-azure-ad/lib/oidcstrategy.js:667:21\n' +
2020-11-03T14:40:42.954949074Z     '    at /home/site/wwwroot/node_modules/async/lib/async.js:52:16\n' +
2020-11-03T14:40:42.954953374Z     '    at /home/site/wwwroot/node_modules/async/lib/async.js:696:30\n' +
2020-11-03T14:40:42.954957574Z     '    at /home/site/wwwroot/node_modules/async/lib/async.js:167:37\n' +
2020-11-03T14:40:42.954961874Z     '    at Immediate.<anonymous> (/home/site/wwwroot/node_modules/async/lib/async.js:1206:34)\n' +
2020-11-03T14:40:42.954978174Z     '    at Shim.applySegment (/home/site/wwwroot/node_modules/newrelic/lib/shim/shim.js:1430:20)\n' +
2020-11-03T14:40:42.954982575Z     '    at Immediate.wrapper (/home/site/wwwroot/node_modules/newrelic/lib/shim/shim.js:2092:17)\n' +
2020-11-03T14:40:42.954986375Z     '    at processImmediate (internal/timers.js:456:21)\n' +
2020-11-03T14:40:42.954990175Z     '    at process.callbackTrampoline (internal/async_hooks.js:120:14)',
2020-11-03T14:40:42.954993975Z   fileName: undefined,
2020-11-03T14:40:42.954997675Z   lineNumber: undefined,
2020-11-03T14:40:42.955001175Z   name: 'AuthenticationError'
2020-11-03T14:40:42.955004875Z } { errorCode: 500, message: 'Unauthorized' }
```

Config
```
    const AuthenticationStrategy = new OIDCStrategy(
      {
        identityMetadata: `https://login.microsoftonline.com/${tenantID}/v2.0/.well-known/openid-configuration`,
        clientID,
        responseType: 'id_token',
        responseMode: 'form_post',
        redirectUrl,
        issuer: `https://sts.windows.net/${tenantID}/v2.0`,
        scope: ['profile'],
        loggingLevel: 'info',
        passReqToCallback: false,
        cookieSameSite: true,
        loggingNoPII: false,
      },
      ...
    );
```

Raised Enterprise Support Request: 120110324006248

**Comment by SigurdMW** [comment]
@phawxby Did you try to configure your cookie to use `sameSite=None`? That solved it for me.

**Comment by phawxby** [comment]
@SigurdMW both the OIDCStrategy cookie and the session cookies are both configured for `sameSite=none`.

Session options
```
const sessionOptions: SessionOptions = {
  secret: 'SNIP',
  resave: false,
  saveUninitialized: true,
  cookie: {
    domain: 'SNIP',
    sameSite: 'none',    <--------------------
    secure: true,
  },
};
```

OIDC
```
    const AuthenticationStrategy = new OIDCStrategy(
      {
        identityMetadata: `https://login.microsoftonline.com/${tenantID}/v2.0/.well-known/openid-configuration`,
        clientID,
        responseType: 'id_token',
        responseMode: 'form_post',
        redirectUrl,
        issuer: `https://sts.windows.net/${tenantID}/v2.0`,
        scope: ['profile'],
        loggingLevel: 'info',
        passReqToCallback: false,
        cookieSameSite: true,       <--------------------
        loggingNoPII: false,
      },
      ...
    );
```

**Comment by SigurdMW** [comment]
@phawxby the `cookieSameSite` option shouldn't have any effect in your case, it should only be used when you have `useCookieInsteadOfSession` I think. 
Does the login error happen on every login request or just sometimes?

**Comment by pjbrigden** [comment]
@phawxby I'm running into the same issue you are. Did you figure out what was wrong?

**Comment by phawxby** [comment]
> @phawxby I'm running into the same issue you are. Did you figure out what was wrong?

Probably over 95% of requests.

**Comment by phawxby** [comment]
> @phawxby I'm running into the same issue you are. Did you figure out what was wrong?

Nope. I've given up bashing my head on the wall.for now and handed it off the MS enterprise support to see if they can figure it out.

**Comment by SigurdMW** [comment]
This issue was resolved by setting `sameSite=None` on the cookie.
