### ISSUE TITLE
Cryptic error message when the client ID is null/undefined

### ISSUE THREAD

**Issue by jeffwilcox** [AzureAD/passport-azure-ad#71]
Hi,
Might be useful to actively protect against a null or undefined/empty client ID when using the module.

This is the cryptic error I get when I set client ID to the empty string, for example...

```
...\node_modules\passport-azure-ad\node_modules\cache-manager\lib\callback_filler.js:13
    waiting.forEach(function(task) {
           ^

TypeError: Cannot read property 'forEach' of undefined
    at CallbackFiller.fill (...\node_modules\passport-azure-ad\node_modules\cache-manager\lib\callback_filler.js:13:12)
    at Domain.<anonymous> (...\node_modules\passport-azure-ad\node_modules\cache-manager\lib\caching.js:85:36)
    at emitOne (events.js:77:13)
    at Domain.emit (events.js:169:7)
    at emitError (domain.js:65:24)
    at Domain.errorHandler [as _errorHandler] (domain.js:104:16)
    at process._fatalException (node.js:218:33)
    at Domain.errorHandler [as _errorHandler] (domain.js:130:26)
    at process._fatalException (node.js:218:33)
```

**Comment by brandwe** [comment]
This is damn strange. I wrote a validator class to do this ahead of time. I assume it's being used before that time. I'll fix.

**Comment by lovemaths** [comment]
done
