### ISSUE TITLE
B2C Claims (Like Email) Not Working

### ISSUE THREAD

**Issue by brandwe** [AzureAD/passport-azure-ad#97]
It appears that B2C changed how claims are delivered and the passport plug-in is not finding them in B2C flows.

```
Error: No email found
   at Strategy._verify (/Volumes/Development HD/SDKs/passport-azure-ad/examples/login-oidc-b2c/app.js:124:19)
   at onProfileLoaded (/Volumes/Development HD/SDKs/passport-azure-ad/lib/passport-azure-ad/oidcstrategy.js:506:22)
   at /Volumes/Development HD/SDKs/passport-azure-ad/lib/passport-azure-ad/oidcstrategy.js:457:17
   at Strategy._shouldLoadUserProfile (/Volumes/Development HD/SDKs/passport-azure-ad/lib/passport-azure-ad/oidcstrategy.js:813:12)
   at /Volumes/Development HD/SDKs/passport-azure-ad/lib/passport-azure-ad/oidcstrategy.js:417:14
   at fn (/Volumes/Development HD/SDKs/passport-azure-ad/node_modules/async/lib/async.js:746:34)
   at /Volumes/Development HD/SDKs/passport-azure-ad/node_modules/async/lib/async.js:1213:16
   at /Volumes/Development HD/SDKs/passport-azure-ad/node_modules/async/lib/async.js:166:37
   at /Volumes/Development HD/SDKs/passport-azure-ad/node_modules/async/lib/async.js:706:43
   at /Volumes/Development HD/SDKs/passport-azure-ad/node_modules/async/lib/async.js:167:37```

**Comment by brandwe** [comment]
B2C server team made emails an array and didn't tell me. Thanks Obama.
